import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/components/AntdRegistry'
import '@/styles/base.sass'
import '@/styles/common.sass'
import { LayoutFooter } from '@/layouts/ly-footer'
import { LayoutHeader } from '@/layouts/ly-header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <StyledComponentsRegistry>
        <body className={inter.className}>
          <LayoutHeader />
          {children}
          <LayoutFooter />
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}
