import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/components/AntdRegistry'
import '@/styles/base.sass'
import '@/styles/common.sass'
import 'animate.css'
import { LayoutFooter } from '@/layouts/ly-footer'
import { LayoutHeader } from '@/layouts/ly-header'
import { LayoutAffix } from '@/layouts/affix'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '安势 - Sectrend',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <StyledComponentsRegistry>
        <body className={inter.className} id="sectrend-site">
          <LayoutHeader />
          {children}
          <LayoutFooter />
          <LayoutAffix />
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}
